### GET root
GET http://localhost:8080
Accept: application/json

### GET healthz
GET http://localhost:8080/v1/healthz
Accept: application/json

### GET err
GET http://localhost:8080/v1/err
Accept: application/json

### POST create user
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "name": "John"
}
